### ISSUE TITLE
Option to set byte order is missing

### ISSUE THREAD

**Issue by meberli** [sourceperl/pyModbusTCP#17]
Im using pyModbusTCP to read out data from a smart meter. 
I'm always getting wrong results when reading data.
Problem seems to be the byte ordering.
For example in Register 4112 my smartmeter stores the baud rate, but read_holding_registers(4112,1) results in [32805] which is not correct. changing byte order from 0x8025 to 0x2580 solves the issue and returns 9600

would be nice to have a default byteorder setting on connection level.

**Comment by sourceperl** [comment]
Hi,

It's not easy to include simple data mangling process directly into pyModbusTCP client since there are a lot of data form :
- 32 bits integers with 2’s complement or not and perhaps also with MSB and LSB words or bytes swap.
- float value
- double value
- bits encoded in word value (i've see cases with strange order)
- ASCII value and so on...

So, to keep thing simple, i don't want to include data mangling directly into ModbusClient.

Some of current data form can be format with tools include in utils part of pyModbusTCP (see https://pymodbustcp.readthedocs.io/en/latest/quickstart/index.html#utils-module-modbus-data-mangling).

We can create a custom one, for your use case, we use  struct like this :
```python
import struct
l_words = [0xff00, 0x00ff]
l_words_swap = [struct.unpack("<H", struct.pack(">H", word))[0] for word in l_words]
```

It's also possible to use inheritance to be near as possible as what you want like in :
https://github.com/sourceperl/pyModbusTCP/blob/master/examples/float_support.py

Have a nice day
Loïc
