### ISSUE TITLE
how to get client drive id from server

### ISSUE THREAD

**Issue by l337quez** [sourceperl/pyModbusTCP#34]
I need to know the client's id .. I have tried several things but I have not been successful .. for example I don't know what the data parameter is, nor the message parameter. I get the registry values for an example in the documentation with getvalues, but I don't know more about the rest. I would infinitely appreciate your help, at least tell me some clues how to do it

**Comment by sourceperl** [comment]
I'm not sure if you still have the problem since October. But, in case, if by "client id" you talk about the modbus "unit_id" then you can try to find out using this code:

```python
import time
from pyModbusTCP.client import ModbusClient

c=ModbusClient(host='yourhost@', auto_open=True, debug=True)
for uid in range(1, 255):
    c.unit_id(uid)
    print('try for unid_id=%i, if we get response value or an except code it\'s the good one' % uid)
    print('read return: %s' % c.read_holding_registers(0))
    time.sleep(.1)
```
For the data parameters on the slave, if you don't have slave documentation, it could be very tricky to discover this. Modbus does not have an automatic discovery mechanism like browsing in OPC-UA protocol for example.
